// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;
using RagPdfApi.Context;

#nullable disable

namespace RagPdfApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251103020909_Criação do banco de dados")]
    partial class Criaçãodobancodedados
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RagPdfApi.Models.Artigo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataArtigo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_artigo");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("titulo");

                    b.HasKey("Id");

                    b.ToTable("artigos", (string)null);
                });

            modelBuilder.Entity("RagPdfApi.Models.ArtigoChunk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<int>("ArtigoId")
                        .HasColumnType("integer")
                        .HasColumnName("artigo_id");

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("conteudo");

                    b.Property<Vector>("Vetor")
                        .IsRequired()
                        .HasColumnType("vector(384)")
                        .HasColumnName("vector");

                    b.HasKey("Id");

                    b.HasIndex("ArtigoId");

                    b.ToTable("artigos_chunks", (string)null);
                });

            modelBuilder.Entity("RagPdfApi.Models.ArtigoChunk", b =>
                {
                    b.HasOne("RagPdfApi.Models.Artigo", "Artigo")
                        .WithMany("ArtigoChunks")
                        .HasForeignKey("ArtigoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artigo");
                });

            modelBuilder.Entity("RagPdfApi.Models.Artigo", b =>
                {
                    b.Navigation("ArtigoChunks");
                });
#pragma warning restore 612, 618
        }
    }
}
